var stack = TwoSideArrayStack<Int>()
stack.pushHead(item: 5)
stack.pushHead(item: 2)
stack.pushHead(item: 3)
stack.pushTail(item: 1)
stack.pushTail(item: 2)
stack.pushTail(item: 1)
print(stack.popHead())
print(stack.popHead())
print(stack.popHead())
print(stack.popHead())
print(stack.popTail())
print(stack.popTail())
print(stack.popTail())
